### ISSUE TITLE
What's the difference between G3D and three.js？

### ISSUE THREAD

**Issue by zhaozhiming** [alibaba/G3D#1]
RT

**Comment by xieguanglei** [comment]
G3D depends on no DOM APIs, so it can run on hybrid environments (Weex or React Native), using [GCanvas](https://github.com/alibaba/GCanvas).

**Comment by zhaozhiming** [comment]
Oh, yes I see. And are there any other different?

**Comment by xieguanglei** [comment]
In addition to the main difference above, there's serveral other differences. 

1. The API and function is different.
2. G3D is smaller in size.
3. The roadmap, G3D is focusing on provide 3D render functions for GCanvas for now.

**Comment by zhaozhiming** [comment]
OK, I see. Thank you.
