### ISSUE TITLE
support webgl2 in roadmap or not?

### ISSUE THREAD

**Issue by chenray844** [alibaba/G3D#2]
@all
https://github.com/alibaba/G3D/blob/0f51448933e8254828473f2a3e2583fee02b3150/src/G3D.Engine.js#L16

this library is using `webgl1` at this moment.     

Does it support `webgl2` in the road-map or not.

https://github.com/alibaba/G3D/blob/0f51448933e8254828473f2a3e2583fee02b3150/src/mesh/G3D.MeshBuilder.js#L156
`MeshBuilder` support some basic geometries. Will it support more geometries in road map or not?

https://github.com/alibaba/G3D/blob/0f51448933e8254828473f2a3e2583fee02b3150/src/parser/G3D.StlParser.js#L1

support more models such as step, iges,  loading?

**Comment by xieguanglei** [comment]
1. support webgl2 is in the roadmap.
2. support more geometries is not in the roadmap for now, any suggestions?
3. support model models is in the roadmap.
