### ISSUE TITLE
[Question] Is it possible to render a texture from another GL context?

### ISSUE THREAD

**Issue by dagatsoin** [alibaba/G3D#24]
I am looking for a 3D engine for React Native to render a Mapbox map as a texture. 
There is an exemple of what I want with unity: https://blog.mapbox.com/mapbox-unity-5ae8fcc7fb7a.

I think it would be possible if render contexte are not isolated. For now, it seems we can share the GL context of Mapbox. But is G3D is also open to "import" a framebuffer ?

**Comment by xieguanglei** [comment]
I'm afraid in G3D that there has been no such cases using framebuffer or texture from another context, but I think it may be a good idea. You may check [framebuffer](https://github.com/alibaba/G3D/blob/master/src/core/framebuffer.ts) and [shader-material](https://github.com/alibaba/G3D/blob/master/src/material/shader-material.ts) source code to see whether there's something can help you.

**Comment by dagatsoin** [comment]
Thanks for you answer. I will investigate that way.
