### ISSUE TITLE
Roadmap for post processing support

### ISSUE THREAD

**Issue by doodlewind** [alibaba/G3D#3]
Hi, this library looks neat and promising!

On Android and iOS there are libraries like [GPUImage](https://github.com/BradLarson/GPUImage) that customize fragment shader for realtime image / video processing, with WebGL I can see [GLFX](https://github.com/evanw/glfx.js) and [Seriously.js](https://github.com/brianchirls/Seriously.js) while they're somewhat old. [Three.js](http://blog.cjgammon.com/threejs-post-processing) also supports similar feature. Wondering any plan for this case?

Thanks.

**Comment by xieguanglei** [comment]
Sure, post processing is cool, and it is in our plan.

Actually there's a [blog](http://taobaofed.org/blog/2018/03/05/intro-to-g3d/) about this library, including the roadmap. (There's only the Chinese version for now.)
