### ISSUE TITLE
请教一下，node 环境下有办法弄出 canvas 对象吗

### ISSUE THREAD

**Issue by forever-z-133** [alibaba/G3D#35]
其实和本项目没太大关系，但始终没找到实现它的办法，所以舔脸来求助了，嘤嘤嘤。

就是想在 node 环境中画图像生成图片这种，我只熟悉 canvas；
但这时候又没有 canvas 对象，也不太清楚后端普遍是怎么做到的。
所以大佬能否给点思路，如何能完成该需求，不考虑 canvas 也行，感恩的心~

**Comment by xieguanglei** [comment]
[node-canvas](https://github.com/Automattic/node-canvas)

**Comment by forever-z-133** [comment]
> [node-canvas](https://github.com/Automattic/node-canvas)

有进行过尝试，node-gyp 经常会安装不上，比如 zeit 部署的时候、和我家的电脑
