### ISSUE TITLE
事件支持：好像还没看到有支持事件的demo或controls。

### ISSUE THREAD

**Issue by hopepdm** [alibaba/G3D#6]
要开发者自己写控件嘛，只能展示的话，有点鸡肋。

**Comment by xieguanglei** [comment]
With G3D you can easily pick and drag a mesh, see the scene#pick method.

https://alibaba.github.io/G3D/docs/Scene.html

Demos will come later.

**Comment by hopepdm** [comment]
@xieguanglei thanks
